apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-app-deployment
spec:
  selector:
    matchLabels:
      app: argo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: argo-app
    spec:
      containers:
      - name: argo-app
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
