apiVersion: apps/v1
kind: Deployment
metadata:
  name: kapp-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kapp-v1
  template:
    metadata:
      labels:
        app: kapp-v1
    spec:
      containers:
        - name: kapp
          image: wil42/playground:v1
          ports:
            - containerPort: 8888
          readinessProbe:
            httpGet:
              path: /
              port: 8888
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8888
            initialDelaySeconds: 10
            periodSeconds: 10
